# App settings
PASSWORD = "1234"

# Cooler settings
COOLER_GPIO_PWM_PIN = 19
COOLER_PWM_FREQ = 1000

# Dispenser settings
DISPENSER_GPIO_PIN = 13
DISPENSER_WORK_TIME = 30  # sec
DISPENSER_MAX_DELAY_TIME = 30  # sec

# Distance
DISTANCE_GPIO_TRIGGER_PIN = 18
DISTANCE_GPIO_ECHO_PIN = 24
DISTANCE_MAX_VALUE = 10  # sm

# Liquid container
LIQUID_EMPTY_PIN = 5
LIQUID_FULL_PIN = 6
LIQUID_PUMP_PIN = 26
LIQUID_MAIN_TANK_PIN = 20

# Temperature sensor
TEMPERATURE_SENSOR_CHANNEL = 0x58
TEMPERATURE_MAX_VALUE = 0.2
TEMPERATURE_MIN_VALUE = 0.0
TEMPERATURE_DELAY = 5  # sec
