# App settings
SCREEN_HIGH = 1280
SCREEN_WIDTH = 720

# Cooler settings
COOLER_GPIO_PWM_PIN = 19
COOLER_PWM_FREQ = 1000

# Dispenser settings
DISPENSER_GPIO_PIN = 13
DISPENSER_WORK_TIME = 30  # sec
DISPENSER_MAX_DELAY_TIME = 30  # sec
