# App settings
PASSWORD = "1234"
FONT_SIZE = 160
ADMIN_BACKGROUND_COLOR = "background-color: rgb(0, 123, 255);"
USER_BACKGROUND_COLOR = "background-color: rgb(255, 255, 200);"
BUTTON_COLOR = 'background-color: rgb(2, 112, 255);'
IMAGE_WIDTH = 100
IMAGE_HEIGHT = 100
QUIT_DELAY = 300  # sec

# Cooler settings
COOLER_GPIO_PWM_PIN = 19
COOLER_PWM_FREQ = 1000

# Dispenser settings
DISPENSER_GPIO_PIN = 13
DISPENSER_WORK_TIME = 30  # sec
DISPENSER_MAX_DELAY_TIME = 30  # sec

# Distance
DISTANCE_GPIO_TRIGGER_PIN = 18
DISTANCE_GPIO_ECHO_PIN = 24
DISTANCE_MAX_VALUE = 15  # sm

# Liquid container
LIQUID_EMPTY_PIN = 5
LIQUID_FULL_PIN = 6
LIQUID_PUMP_PIN = 26
LIQUID_MAIN_TANK_PIN = 20

# Temperature sensor
TEMPERATURE_SENSOR_CHANNEL = 0x58
TEMPERATURE_MAX_VALUE = 17.2
TEMPERATURE_MIN_VALUE = 25.0
TEMPERATURE_DELAY = 5  # sec
